<a href="https://colab.research.google.com/github/Taheri1400/machine-learning-projects/blob/main/income.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
درآمد
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
مقدمه و صورت مسئله
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    در این تمرین قصد داریم درخت تصمیمی بسازیم که قادر باشد با دریافت یک سری ویژگی‌های شخصی و شغلی از شهروندان آمریکایی پیش‌بینی کند آیا شخص درآمد سالانه‌ی بالای ۵۰ هزار دلار خواهد داشت یا خیر. مجموعه‌داده‌ی مورداستفاده و صورت مسئله بسیار خوش‌تعریف است، با این حال جهت پیش‌پردازش مناسب ویژگی‌ها و همچنین دست‌یابی به یک مدل  با عملکرد بالا نیاز است از تکنیک‌های مختلف مهندسی ویژگی و فوت‌و‌فن‌های مرتبط با درخت تصمیم که در درسنامه‌ها آموخته‌اید استفاده کنید. بهره‌گیری از این تکنیک‌ها جهت مواجهه با چالش‌های عملی می‌تواند به‌خوبی شما را برای استفاده از این مدل در دنیای واقعی آماده کند.‌
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
وارد کردن کتابخانه‌های مورد نیاز
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    ابتدا کتابخانه‌های مورد نیازتان را وارد کنید.
</font>
</p>

In [ ]:
import numpy as np
import pandas as pd

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
معرفی مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    هر نمونه از این مجموعه‌داده با ویژگی‌هایی که در جدول زیر شرح داده شده همراه است. ستون <code>income</code> متغیر هدف مسئله است که درآمد شخص را نشان می‌دهد.
</font>
</p>
<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|age|سن|
|workclass|یک عبارت کلی که نشان‌دهنده‌ی وضعیت شغلی فرد است.|
|fnlwgt|وزن نهایی، به عبارت دیگر تعداد افرادی که سرشماری باور دارد این ردیف بازنمایی می‌کند (نماینده‌ی آنهاست). |
|education|بیشترین سطح تحصیلات فرد |
|education.num|بیشترین سطح تحصیلات فرد به شکل عددی |
|marital.status|وضعیت تاهل فرد. توجه شود که <code>Married-­civ-­spouse</code> به معنی همسر غیرنظامی و <code>Married-­AF-­spouse</code> به معنی همسر نظامی است.|
|occupation|نوع کلی شغل یک فرد |
|relationship|رابطه‌ی این فرد با دیگران، به عنوان مثال همسر (<code>Husband</code>). هر داده تنها دارای یک رابطه است. |
|race|نژاد |
|sex| جنسیت بیولوژیکی فرد |
|capital.gain|سود سرمایه‌ی فرد  |
|capital.loss| زیان سرمایه‌ی فرد |
|hours.per.week| ساعت‌هایی که فرد گزارش داده در یک هفته کار می‌کند. |
|native.country| سرزمین مادری |
|income|درآمد، کمتر یا مساوی ۵۰ هزار دلار (<code dir=ltr><=50K</code>) یا بیشتر از آن (<code dir=ltr>>50K</code>) |

</font>
</div>
</center>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
خواندن مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    در ابتدا نیاز است فایل‌های مجموعه‌داده را بخوانید. نمونه‌های آموزشی در فایل <code>train.csv</code> و نمونه‌های آزمون که باید دسته‌ی آن‌ها را پیش‌بینی کنید در فایل <code>test.csv</code> ذخیره شده‌اند. اگر لازم دانستید می‌توانید به دلخواه خود بخشی از مجموعه‌ی آموزشی را به عنوان مجموعه‌ی اعتبارسنجی نیز جدا کنید.
</font>
</p>

In [ ]:
train_data = pd.read_csv('train.csv')
train_data

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,40,Self-emp-not-inc,223881,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,99999,0,70,United-States,>50K
1,30,Private,149118,HS-grad,9,Divorced,Craft-repair,Not-in-family,White,Female,0,0,40,United-States,<=50K
2,46,Private,109209,Some-college,10,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,>50K
3,32,Private,229566,Assoc-voc,11,Married-civ-spouse,Other-service,Husband,White,Male,0,0,60,United-States,>50K
4,54,?,148657,Preschool,1,Married-civ-spouse,?,Wife,White,Female,0,0,40,Mexico,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,40,Private,130834,Some-college,10,Never-married,Adm-clerical,Not-in-family,White,Female,0,0,40,United-States,<=50K
24996,31,Local-gov,33124,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,50,United-States,<=50K
24997,38,Federal-gov,190895,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,?,>50K
24998,23,Private,420973,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,40,United-States,<=50K
24999,60,Private,88055,10th,6,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,<=50K

In [ ]:
test_data = pd.read_csv('test.csv')
test_data

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country
0,31,Private,176711,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,38,United-States
1,40,Private,120277,Some-college,10,Never-married,Sales,Not-in-family,White,Male,0,0,40,United-States
2,43,Private,299197,Some-college,10,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States
3,70,Self-emp-inc,188260,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,16,United-States
4,51,Private,254211,Bachelors,13,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,20,United-States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7159,37,Self-emp-not-inc,75050,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,55,United-States
7160,36,Private,156780,HS-grad,9,Never-married,Sales,Other-relative,Asian-Pac-Islander,Female,0,0,40,?
7161,34,Private,381153,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States
7162,59,Private,294395,Masters,14,Widowed,Prof-specialty,Not-in-family,White,Female,0,0,40,United-States
7163,24,State-gov,506329,Some-college,10,Never-married,Adm-clerical,Own-child,Asian-Pac-Islander,Male,0,0,40,?

In [ ]:
train_data.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

In [ ]:
train_data.replace('?', np.nan, inplace=True)

In [ ]:
test_data.replace('?', np.nan, inplace=True)

In [ ]:
test_data.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
dtype: int64

In [ ]:
train_data.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
پیش‌پردازش و مهندسی ویژگی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    در این سوال شما می‌توانید از هر تکنیک پیش‌پردازش/مهندسی ویژگی که در فصل‌های گذشته آموختید، استفاده کنید. توجه داشته باشید که انتخاب شما در بخش بعدی یعنی مدل‌سازی می‌تواند مراحلی که در این بخش طی می‌کنید را تحت تاثیر قرار دهد. بنابراین پیشنهاد می‌کنیم مواردی همچون مدیریت مقادیر گم‌شده، ویژگی‌های دسته‌ای و غیره را پس از مطالعه‌ی بخش بعد انجام دهید.
    <br>
    تکنیک‌هایی که در این بخش استفاده می‌کنید به شکل مستقیم مورد ارزیابی توسط سامانه داوری قرار <b>نمی‌گیرند.</b> بلکه همه آن‌ها در دقت مدل شما تاثیر خواهند گذاشت؛ بنابراین هر چه پیش‌پردازش/مهندسی ویژگی بهتری انجام دهید تا دقت مدل بهبود پیدا کند، امتیاز بیشتری از این سوال کسب خواهید کرد.
</font>
</p>

In [ ]:
for col in ['workclass', 'occupation', 'native.country']:
    train_data[col].fillna(train_data[col].mode()[0], inplace=True)

/tmp/ipython-input-6-2339628500.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_data[col].fillna(train_data[col].mode()[0], inplace=True)

In [ ]:
for col in ['workclass', 'occupation', 'native.country']:
    test_data[col].fillna(train_data[col].mode()[0], inplace=True)

/tmp/ipython-input-7-2748210301.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test_data[col].fillna(train_data[col].mode()[0], inplace=True)

In [ ]:
train_data.drop(columns=['education'], inplace=True)
test_data.drop(columns=['education'], inplace=True)

In [ ]:
from sklearn.preprocessing import LabelEncoder

# پیدا کردن ستون‌های دسته‌ای
categorical_cols = train_data.select_dtypes(include='object').columns.tolist()
categorical_cols.remove('income')  # متغیر هدف را جدا می‌کنیم

# ترکیب داده‌های آموزشی و تست برای رمزگذاری یکنواخت
combined_data = pd.concat([train_data[categorical_cols], test_data[categorical_cols]], axis=0)

# Label Encoding برای هر ستون دسته‌ای
label_encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    combined_data[col] = le.fit_transform(combined_data[col])
    label_encoders[col] = le

# بازگرداندن به train و test
train_data[categorical_cols] = combined_data[:len(train_data)][categorical_cols]
test_data[categorical_cols] = combined_data[len(train_data):][categorical_cols]

# رمزگذاری متغیر هدف
train_data['income'] = train_data['income'].map({'<=50K': 0, '>50K': 1})

In [ ]:
train_data

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,40,5,223881,14,15,2,9,0,4,1,99999,0,70,38,1
1,30,3,149118,11,9,0,2,1,4,0,0,0,40,38,0
2,46,3,109209,15,10,2,0,0,4,1,0,0,40,38,1
3,32,3,229566,8,11,2,7,0,4,1,0,0,60,38,1
4,54,3,148657,13,1,2,9,5,4,0,0,0,40,25,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,40,3,130834,15,10,4,0,1,4,0,0,0,40,38,0
24996,31,1,33124,9,13,4,9,1,4,0,0,0,50,38,0
24997,38,0,190895,9,13,2,9,0,4,1,0,0,40,38,1
24998,23,3,420973,9,13,4,9,1,4,0,0,0,40,38,0
24999,60,3,88055,0,6,2,13,0,4,1,0,0,40,38,0

In [ ]:
def remove_outliers_iqr(df, numerical_columns, k=1.5):
    """
    حذف داده‌های پرت از ستون‌های عددی با استفاده از روش IQR.
    k: ضریب برای مشخص‌کردن فاصله از چارک‌ها (معمولاً ۱.۵)
    """
    for col in numerical_columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - k * IQR
        upper_bound = Q3 + k * IQR

        # فقط داده‌هایی که در محدوده مجاز قرار دارند را نگه می‌داریم
        df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]

    return df

In [ ]:
train_data

,age,workclass,fnlwgt,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,40,5,223881,15,2,9,0,4,1,99999,0,70,38,1
1,30,3,149118,9,0,2,1,4,0,0,0,40,38,0
2,46,3,109209,10,2,0,0,4,1,0,0,40,38,1
3,32,3,229566,11,2,7,0,4,1,0,0,60,38,1
4,54,3,148657,1,2,9,5,4,0,0,0,40,25,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,40,3,130834,10,4,0,1,4,0,0,0,40,38,0
24996,31,1,33124,13,4,9,1,4,0,0,0,50,38,0
24997,38,0,190895,13,2,9,0,4,1,0,0,40,38,1
24998,23,3,420973,13,4,9,1,4,0,0,0,40,38,0
24999,60,3,88055,6,2,13,0,4,1,0,0,40,38,0

In [ ]:
from sklearn.model_selection import train_test_split

X = train_data.drop(columns='income')
y = train_data['income']

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
مدل‌سازی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    حال که داده را پاکسازی کرده و احتمالا ویژگی‌هایی را به آن افزوده یا از آن حذف کرده‌اید، وقت آن است که مدلی آموزش دهید که بتواند متغیر هدف این مسئله را پیش‌بینی کند. در این تمرین انتخاب کتابخانه‌ای که درخت تصمیم را در اختیارتان بگذارد به عهده‌ی خود شماست. می‌توانید همچون همیشه از کتابخانه‌ی <code>scikit-learn</code> استفاده کنید اما توجه داشته باشید که درخت تصمیم این کتابخانه از قابلیت‌های مهمی مثل مدیریت مستقیم مقادیر گم‌شده و ویژگی‌های دسته‌ای پشتیبانی نمی‌کند و نیاز خواهید داشت که مراحل پیش‌پردازش مختلفی را انجام دهید. اما پیشنهاد بهتر این است که با توجه به توضیحاتی که در ادامه خواهیم داد از کتابخانه‌ی <code>H2O</code> استفاده کنید که از قابلیت‌های ذکرشده پشتیبانی می‌کند و نیازی به طی کردن مراحل اضافی نیست (البته معمولاً عملکرد درخت تصمیم این کتابخانه هم بهتر از درخت تصمیم <code>scikit-learn</code> است). با این حال ما مقدار آستانه‌ی پاس شدن این تمرین را به‌گونه‌ای تنظیم کرده‌ایم که متعادل باشد و با هر دو روش بتوانید امتیاز موردنظر را کسب کنید. حتی می‌توانید خفن‌تر (😎) عمل کرده و با هرکدام از کتابخانه‌ها درخت تصمیمی بسازید و عملکرد آن‌ها را مقایسه کنید.
</font>
</p>

<h3 align=right style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
    استفاده از <code>scikit-learn</code>
</font>
</h3>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    به منظور استفاده از درخت تصمیم برای مسائل دسته‌بندی می‌توانید از <code>DecisionTreeClassifier</code> موجود در کتابخانه‌ی <code>scikit-learn</code> استفاده کنید. نحوه‌ی آموزش مدل و پیش‌بینی برای نمونه‌های جدید همچون تمام مدل‌های این کتابخانه است، اما برخی پارامترها و آرگومان‌های بسیار کاربردی این کلاس در جدول زیر شرح داده شده‌اند. جهت بررسی پارامترها و توضیحات بیشتر می‌توانید از <a href="https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html#sklearn.tree.DecisionTreeClassifier" target="__blank">این لینک</a>، سند اصلی آن را مطالعه کنید.
</font>
</p>

<center>
<p dir=ltr style="direction: ltr; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    <code dir=ltr>from sklearn.tree import DecisionTreeClassifier</code>
    <br>
    <code dir=ltr>clf = DecisionTreeClassifier()</code>
</font>
</p>
</center>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    
|پارامتر|توضیحات|مقادیر ممکن|مقدار پیش‌فرض|
|:------:|:---:|:---:|:---:|
|<code>criterion</code>|معیار ارزیابی تفکیک (معیار ناخالصی یا بهره اطلاعاتی)|<code>"gini"</code>، <code>"entropy"</code> یا <code>"log_loss"</code>|<code>"gini"</code>|
|<code>max_depth</code>|حداکثر عمق درخت|عدد <code>int</code>|<code>None</code>|
|<code>min_samples_split</code>|حداقل نمونه‌ها جهت تفکیک یک گره‌ی داخلی|عدد <code>int</code> (تعداد) یا <code>float</code> (درصد)|<code>2</code>|
|<code>min_samples_leaf</code>|حداقل نمونه‌های یک برگ. یک گره تنها در صورتی تفکیک می‌یابد که هرکدام از شاخه‌های راست و چپ آن حداقل شامل این تعداد نمونه باشد|عدد <code>int</code> (تعداد) یا <code>float</code> (درصد)|<code>1</code>|
|<code>max_features</code>|تعداد ویژگی‌هایی که در هنگام جستجوی بهترین تفکیک بررسی می‌شوند|عدد <code>int</code> (تعداد)، <code>float</code> (درصد)، ، <code>"sqrt"</code> (جذر)، <code>"log2"</code> (لگاریتم در مبنای ۲) یا <code>None</code> (تمام ویژگی‌ها)|<code>None</code>|
|<code>min_impurity_decrease</code>|یک گره هنگامی تفکیک می‌شود که آن تفکیک باعث کاهش ناخالصی بیشتر یا مساوی این مقدار شود|عدد <code>float</code>|<code>0.0</code>|
    
</font>
</div>
</center>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    <b>نکته:</b>
    پارامتر کاربردی دیگری به نام <code>ccp_alpha</code> وجود دارد که به منظور پس‌هرس درخت تصمیم با روش Minimal Cost-Complexity استفاده می‌شود. از آنجا که شرح این تکنیک خارج از بحث این فصل است، ضرورتی بر استفاده از آن تعریف نشده است. اما در صورت علاقه می‌توانید برای مطالعه‌ی این روش جذاب به بخش <a href="https://scikit-learn.org/stable/modules/tree.html#minimal-cost-complexity-pruning" target="__blank">معرفی آن</a> در <code>scikit-learn</code> یا فصل سوم کتاب <i>Classification and Regression Trees</i> نوشته‌ی <i>Leo Breiman</i> مراجعه کرده و یا به شکلی ساده‌تر و جذاب‌تر <a href="https://youtu.be/D0efHEJsfHo" target="__blank">این ویدیو</a> را از <i>StatQuest</i> مشاهده کنید.  
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    اگر مدل را <code>clf</code> بنامیم، پس از آموزش آن می‌توانید به کمک توابع یا متغیرهای زیر، برخی ویژگی‌های مهم درخت تصمیم را مورد بررسی قرار دهید.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    
|پارامتر|توضیحات|
|:------:|:---:|
| <code dir=ltr>clf.get_depth()</code> | عمق درخت |
| <code dir=ltr>clf.get_n_leaves()</code> | تعداد برگ‌های درخت |
| <code dir=ltr>clf.feature_names_in_</code> | ویژگی‌های ورودی |
| <code dir=ltr>clf.feature_importances_</code> | اهمیت هر ویژگی طبق معیار ناخالصی |
    
</font>
</div>
</center>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    همچنین طبق کد زیر می‌توانید به کمک تابع <code>plot_tree</code> درخت تصمیم خود را ترسیم کنید. البته در صورتی‌که درخت حاصل بزرگ باشد ترسیم آن چندان جالب به نظر نخواهد رسید.
</font>
</p>

<center>
<p dir=ltr style="direction: ltr; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    <code dir=ltr>from sklearn import tree</code>
    <br>
    <code dir=ltr>tree.plot_tree(clf)</code>
</font>
</p>
</center>

<h3 align=right style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
    استفاده از <code>H2O</code>
</font>
</h3>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    در کتابخانه‌ی <code>H2O</code> درخت تصمیم به‌صورت مشخص پیاده‌سازی نشده اما به کمک ترفندی که شرح خواهیم داد می‌توانید به یک درخت تصمیم دست یابید. در این کتابخانه مدل‌های حرفه‌ای‌تری پیاده‌سازی شده که در واقع اساس آن‌ها درخت تصمیم است. یکی از این مدل‌ها «<i>جنگل تصادفی</i>» نام دارد که در این کتابخانه با نام <code>H2ORandomForestEstimator</code> در دسترس است و در فصل یادگیری تجمعی کاملاً با ساختار آن آشنا خواهید شد. این مدل در واقع متشکل از تعداد زیادی درخت تصمیم است. بنابراین اگر ما یک جنگل تصادفی بسازیم که تنها شامل یک درخت باشد  در واقع مدل همانند یک درخت تصمیم عمل خواهد کرد. البته نیاز است به شکل زیر برخی از پارامترهای آن را به گونه‌ای مقداردهی کنیم که رفتاری شبیه به درخت تصمیم داشته باشد.
</font>
</p>

<center>
<p dir=ltr style="direction: ltr; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
<code>from h2o.estimators import H2ORandomForestEstimator</code>
<br>
<code>model = H2ORandomForestEstimator(ntrees=1, sample_rate=1)</code>
</font>
</p>
</center>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    برخی از پارامترهای کاربردی این کلاس نیز در جدول زیر معرفی و شرح داده شده است. جهت بررسی پارامترها و توضیحات بیشتر می‌توانید از <a href="https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/drf.html" target="__blank">این لینک</a>، سند اصلی آن را مطالعه کنید.
</font>
</p>


<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    
|پارامتر|توضیحات|مقادیر ممکن|مقدار پیش‌فرض|
|:------:|:-----:|:---:|:---:|
|<code>mtries</code>|تعداد ویژگی‌هایی که به‌صورت تصادفی در هر سطح برای جستجوی بهترین تفکیک استفاده می‌شود| <code dir=ltr>-1</code> برای جذر، <code dir=ltr>-2</code> برای تمام ویژگی‌ها یا عدد بزرگتر یا مساوی <code>1</code> |<code dir=ltr>-1</code>|
|<code>max_depth</code>|حداکثر عمق درخت|عدد <code>int</code>|<code>20</code>|
|<code>min_rows</code>|حداقل نمونه‌های یک برگ. یک گره تنها در صورتی تفکیک می‌یابد که هرکدام از شاخه‌های راست و چپ آن حداقل شامل این تعداد نمونه باشد|عدد <code>int</code>|<code>1</code>|
|<code>min_split_improvement</code>|یک گره هنگامی تفکیک می‌شود که کاهش مربعات خطا حداقل به این میزان بهبود یابد|عدد کوچک (پیشنهاد می‌شود در بازه‌ی <code>1e-10</code> تا <code>1e-3</code> باشد)|<code>1e-05</code>|
|<code>categorical_encoding</code>|رویکرد مدیریت ویژگی‌های دسته‌ای|<code>"auto"</code> (به‌صورت پیش‌فرض معادل <code>"enum"</code>)، <code>"enum"</code> (پشتیبانی مستقیم از ویژگی دسته‌ای)، <code>"one_hot_explicit"</code> (کدگذاری one-hot)،  <code>"binary"</code> (کدگذاری باینری)، <code>"label_encoder"</code> (برچسب‌گذاری) و غیره|<code>"auto"</code>|
|<code>balance_classes</code>|متوازن‌سازی مجموعه‌داده به کمک نمونه‌افزایی کلاس اقلیت|<code>True</code> یا <code>False</code>|<code>False</code>|
|<code>nfolds</code>|تعداد قطعه‌ها در اعتبارسنجی متقاطع (cross-validation)|عدد <code>int</code>|<code>0</code>|
    
</font>
</div>
</center>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    برای استفاده از <code>H2O</code> پیش از هرچیز نیاز است مراحل راه‌اندازی آن را که در درسنامه‌ی مربوط به این کتابخانه شرح داده شد اجرا کرده باشید و همچنین دیتافریم‌های خود را به <code>H2OFrame</code> تبدیل کرده باشید. پس از آن می‌توانید به کمک مدل معرفی‌شده در بالا پارامترهای موردنظر خود را مقداردهی کنید. سپس جهت آموزش مدل نیاز است تابع <code dir=ltr>fit()</code> را با سه آرگومان مهم زیر صدا بزنید.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    
|پارامتر|توضیحات|
|:------:|:-----:|
|<code>x</code>| لیستی شامل نام ستون‌های ورودی (ویژگی‌ها) |
|<code>y</code>| نام ستون متغیر هدف |
|<code>training_frame</code>| داده‌های آموزشی از جنس <code>H2OFrame</code> |
|<code>validation_frame</code>| داده‌های اعتبارسنجی از جنس <code>H2OFrame</code> (دلخواه)|

    
</font>
</div>
</center>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    جهت پیش‌بینی نیز می‌توانید <code>H2OFrame</code> موردنظر خود را به تابع <code dir=ltr>predict()</code> بدهید تا مدل شروع به پیش‌بینی متغیر هدف برای نمونه‌های موردنظر شما کند. توجه داشته باشید که اگر قصد دارید مقادیر پیش‌بینی‌شده را به یک دیتافریم <code>pandas</code> تبدیل کنید می‌توانید از تابع <code dir=ltr>as_data_frame()</code> استفاده کنید. مقادیر پیش‌بینی‌شده در ستونی به نام <code>predict</code> در دیتافریم به‌دست‌آمده ذخیره شده‌اند.
</font>
</p>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
آموزش مدل
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    اکنون وقت آن رسیده که با توجه به کتابخانه‌ی انتخابی، مدل را آموزش دهید.
</font>
</p>

In [ ]:
model = H2ORandomForestEstimator(ntrees=1, sample_rate=1, mtries=-2, max_depth=10,
                                 min_rows=8, min_split_improvement=1e-4,
                                 balance_classes=True, nfolds=5)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

# ساخت مدل
clf = DecisionTreeClassifier(
    criterion='gini',       # یا 'entropy'
    max_depth=10,           # عدد بهینه را با آزمون و خطا پیدا کن
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42
)

# آموزش مدل
clf.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=10, min_samples_leaf=5, min_samples_split=10,
                       random_state=42)

In [ ]:
!pip install h2o

Requirement already satisfied: h2o in /usr/local/lib/python3.11/dist-packages (3.46.0.7)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from h2o) (2.32.3)
Requirement already satisfied: tabulate in /usr/local/lib/python3.11/dist-packages (from h2o) (0.9.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->h2o) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->h2o) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->h2o) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->h2o) (2025.6.15)

In [ ]:
import h2o
from h2o.frame import H2OFrame

# راه‌اندازی سرور H2O
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "11.0.27" 2025-04-15; OpenJDK Runtime Environment (build 11.0.27+6-post-Ubuntu-0ubuntu122.04); OpenJDK 64-Bit Server VM (build 11.0.27+6-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.11/dist-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmpvjdm60ty
  JVM stdout: /tmp/tmpvjdm60ty/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmpvjdm60ty/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.
Warning: Your H2O cluster version is (3 months and 9 days) old.  There may be a newer version available.
Please download and install the latest version from: https://h2o-release.s3.amazonaws.com/h2o/latest_stable.html

--------------------------  -----------------------------------------------------------------------------------------
H2O_cluster_uptime:         04 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.7
H2O_cluster_version_age:    3 months and 9 days
H2O_cluster_name:           H2O_from_python_unknownUser_ktv66e
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.170 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null, "colab_language_server": "/usr/colab/bin/language_service"}
H2O_internal_security:      False
Python_version:             3.11.13 final
--------------------------  -----------------------------------------------------------------------------------------

In [ ]:
from sklearn.model_selection import train_test_split

target_col = 'income'
# فرض می‌کنیم train_data همان دیتافریم اصلی است
train_df, val_df = train_test_split(train_data, test_size=0.2, random_state=42)

hf_train = h2o.H2OFrame(train_df)
hf_valid = h2o.H2OFrame(val_df)
hf_test = h2o.H2OFrame(test_data)

hf_train[target_col] = hf_train[target_col].asfactor()
hf_valid[target_col] = hf_valid[target_col].asfactor()
# همه ستون‌ها بجز ستون هدف
feature_cols = list(train_data.columns)
feature_cols.remove(target_col)  # حذف ستون هدف از لیست ویژگی‌ها

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

In [ ]:
from h2o.estimators import H2ORandomForestEstimator

model = H2ORandomForestEstimator(ntrees=1, sample_rate=1, mtries=-2, max_depth=10,
                                 min_rows=8, min_split_improvement=1e-4,
                                 balance_classes=True, nfolds=5)

model.train(x=feature_cols, y=target_col, training_frame=hf_train, validation_frame=hf_valid)

drf Model Build progress: |██████████████████████████████████████████████████████| (done) 100%

Model Details
=============
H2ORandomForestEstimator : Distributed Random Forest
Model Key: DRF_model_python_1751862547603_1


Model Summary:
    number_of_trees    number_of_internal_trees    model_size_in_bytes    min_depth    max_depth    mean_depth    min_leaves    max_leaves    mean_leaves
--  -----------------  --------------------------  ---------------------  -----------  -----------  ------------  ------------  ------------  -------------
    1                  1                           3188                   10           10           10            237           237           237

ModelMetricsBinomial: drf
** Reported on train data. **

MSE: NaN
RMSE: NaN
LogLoss: NaN
Mean Per-Class Error: NaN
AUC: NaN
AUCPR: NaN
Gini: NaN

ModelMetricsBinomial: drf
** Reported on validation data. **

MSE: 0.10667861445145181
RMSE: 0.3266169230940917
LogLoss: 0.6410643918763458
Mean Per-Class Error: 0.2026492120278718
AUC: 0.8843357451109365
AUCPR: 0.7598711039135992
Gini: 0.768671490221873

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.4067266467866016
       <=50K    >50K    Error    Rate
-----  -------  ------  -------  --------------
<=50K  3340     415     0.1105   (415.0/3755.0)
>50K   367      878     0.2948   (367.0/1245.0)
Total  3707     1293    0.1564   (782.0/5000.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.406727     0.691883  31
max f2                       0.136596     0.779489  65
max f0point5                 0.621609     0.714433  13
max accuracy                 0.548935     0.8514    19
max precision                1            0.965517  0
max recall                   0            1         103
max specificity              1            0.997071  0
max absolute_mcc             0.406727     0.587325  31
max min_per_class_accuracy   0.345274     0.814913  37
max mean_per_class_accuracy  0.286118     0.819668  41
max tns                      1            3744      0
max fns                      1            937       0
max fps                      0            3755      103
max tps                      0            1245      103
max tnr                      1            0.997071  0
max fnr                      1            0.75261   0
max fpr                      0            1         103
max tpr                      0            1         103

Gains/Lift Table: Avg response rate: 24.90 %, avg score: 24.72 %
group    cumulative_data_fraction    lower_threshold    lift       cumulative_lift    response_rate    score       cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  ---------  -----------------  ---------------  ----------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------  --------------------
1        0.0638                      1                  3.87758    3.87758            0.965517         1           0.965517                    1                   0.24739         0.24739                    287.758   287.758            0.24446
2        0.1436                      0.738493           2.78809    3.27214            0.694236         0.743828    0.814763                    0.857643            0.22249         0.46988                    178.809   227.214            0.43446
3        0.1806                      0.621609           2.36622    3.08654            0.589189         0.623556    0.768549                    0.809685            0.0875502       0.55743                    136.622   208.654            0.501771
4        0.2032                      0.602773           2.27459    2.99624            0.566372         0.603037    0.746063                    0.786701            0.0514056       0.608835                   127.459   199.624            0.540127
5        0.3388                      0.365362           1.51639    2.40395            0.377581         0.393446    0.598583                    0.629306            0.205622        0.814458                   51.639    140.395            0.633366
6        0.4                         0.182424           0.892459   2.17269            0.222222         0.261174    0.541                       0.572982            0.0546185       0.869076                   -10.7541  117.269            0.624602
7        0.509                       0.069808           0.552669   1.82577            0.137615         0.125939    0.454617                    0.47725             0.060241        0.929317                   -44.7331  82.5771            0.559677
8        0.6038                      0.0105531          0.288072   1.58434            0.07173          0.0307245   0.394501                    0.407143            0.0273092       0.956627                   -71.1928  58.4343            0.469809
9        0.703                       0.0083304          0.0566783  1.36878            0.0141129        0.0101728   0.340825                    0.351127            0.00562249      0.962249                   -94.3322  36.8775            0.345205
10       0.9472                      0.000292983        0.0296024  1.02352            0.00737101       0.00133808  0.254856                    0.260947            0.00722892      0.969478                   -97.0398  2.35198            0.0296643
11       1                           0                  0.57807    1                  0.143939         0           0.249                       0.247169            0.0305221       1                          -42.193   0                  0

ModelMetricsBinomial: drf
** Reported on cross-validation data. **

MSE: 0.10397596506943058
RMSE: 0.322453043200759
LogLoss: 0.7287449893793788
Mean Per-Class Error: 0.18311951754385963
AUC: 0.8861390830592105
AUCPR: 0.7553846548596356
Gini: 0.772278166118421

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.3347831424876379
       <=50K    >50K    Error    Rate
-----  -------  ------  -------  ----------------
<=50K  12594    2606    0.1714   (2606.0/15200.0)
>50K   935      3865    0.1948   (935.0/4800.0)
Total  13529    6471    0.1771   (3541.0/20000.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.334783     0.685831  144
max f2                       0.106334     0.773277  290
max f0point5                 0.714241     0.721287  32
max accuracy                 0.57169      0.85565   72
max precision                1            0.944785  0
max recall                   0            1         399
max specificity              1            0.995263  0
max absolute_mcc             0.489406     0.586687  93
max min_per_class_accuracy   0.298315     0.816118  165
max mean_per_class_accuracy  0.263129     0.818339  185
max tns                      1            15128     0
max fns                      1            3568      0
max fps                      0            15200     399
max tps                      0            4800      399
max tnr                      1            0.995263  0
max fnr                      1            0.743333  0
max fpr                      0            1         399
max tpr                      0            1         399

Gains/Lift Table: Avg response rate: 24.00 %, avg score: 24.01 %
group    cumulative_data_fraction    lower_threshold    lift       cumulative_lift    response_rate    score        cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  ---------  -----------------  ---------------  -----------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------  --------------------
1        0.0652                      1                  3.93661    3.93661            0.944785         1            0.944785                    1                   0.256667        0.256667                   293.661   293.661            0.25193
2        0.11075                     0.735627           2.96835    3.53837            0.712404         0.759859     0.84921                     0.901233            0.135208        0.391875                   196.835   253.837            0.369901
3        0.1522                      0.620996           2.80458    3.33853            0.6731           0.698112     0.801248                    0.845916            0.11625         0.508125                   180.458   233.853            0.468322
4        0.20865                     0.52374            2.19959    3.03039            0.527901         0.571955     0.727295                    0.771796            0.124167        0.632292                   119.959   203.039            0.557423
5        0.30005                     0.370029           1.49754    2.56346            0.359409         0.403654     0.615231                    0.659654            0.136875        0.769167                   49.7538   156.346            0.617259
6        0.4                         0.162367           1.07137    2.19063            0.257129         0.269707     0.52575                     0.562216            0.107083        0.87625                    7.1369    119.063            0.626645
7        0.50015                     0.0640775          0.551256   1.86236            0.132302         0.117853     0.446966                    0.473237            0.0552083       0.931458                   -44.8744  86.2358            0.567511
8        0.60215                     0.0107926          0.202206   1.58114            0.0485294        0.0259372    0.379474                    0.397467            0.020625        0.952083                   -79.7794  58.114             0.460439
9        0.7087                      0.00136002         0.066479   1.35342            0.015955         0.00680842   0.32482                     0.338733            0.00708333      0.959167                   -93.3521  35.3417            0.329561
10       0.8161                      0.0003602          0.0174581  1.1776             0.00418994       0.000529292  0.282625                    0.294225            0.001875        0.961042                   -98.2542  17.7603            0.190713
11       1                           0                  0.211845   1                  0.0508428        0            0.24                        0.240117            0.0389583       1                          -78.8155  0                  0

Cross-Validation Metrics Summary:
                         mean        sd            cv_1_valid    cv_2_valid    cv_3_valid    cv_4_valid    cv_5_valid
-----------------------  ----------  ------------  ------------  ------------  ------------  ------------  ------------
accuracy                 0.83662194  0.016977258   0.8215497     0.8439405     0.8209176     0.8351145     0.86158746
aic                      nan         0.0           nan           nan           nan           nan           nan
auc                      0.8858479   0.010482503   0.8764867     0.87529564    0.88949805    0.88708836    0.9008708
err                      0.16337804  0.016977258   0.1784503     0.1560595     0.1790824     0.16488549    0.13841255
err_count                652.6       59.638912     684.0         640.0         726.0         648.0         565.0
f0point5                 0.657515    0.027136836   0.6353039     0.6655643     0.6399812     0.64527565    0.7014499
f1                       0.69030964  0.014471555   0.69049776    0.6680498     0.69237286    0.69201523    0.7086127
f2                       0.7285667   0.0362173     0.75619423    0.6705539     0.7541074     0.74605453    0.7159233
lift_top_group           3.9394066   0.13863778    3.8607917     4.0246773     3.7315745     4.0396986     4.040291
loglikelihood            nan         0.0           nan           nan           nan           nan           nan
---                      ---         ---           ---           ---           ---           ---           ---
mcc                      0.5869043   0.019341167   0.5807329     0.56606543    0.58003813    0.58964694    0.61803806
mean_per_class_accuracy  0.80934775  0.014198652   0.81679237    0.7842556     0.814557      0.8184719     0.8126619
mean_per_class_error     0.19065224  0.014198652   0.18320766    0.21574438    0.18544297    0.18152808    0.18733813
mse                      0.10397026  0.0047947094  0.10612412    0.10793351    0.10817163    0.09941247    0.09820957
pr_auc                   0.7557138   0.01632797    0.7618158     0.7271023     0.7580566     0.76487154    0.76672304
precision                0.6381107   0.040575743   0.60316205    0.66391754    0.60924685    0.6174724     0.6967546
r2                       0.42996427  0.021600166   0.42870194    0.39712685    0.4251587     0.4476177     0.45121613
recall                   0.7578632   0.059018414   0.8074074     0.6722338     0.80176646    0.787027      0.7208814
rmse                     0.32237506  0.0074641155  0.32576698    0.32853237    0.32889456    0.31529742    0.31338406
specificity              0.8608323   0.037415016   0.8261773     0.8962774     0.82734764    0.8499168     0.9044423
[22 rows x 8 columns]


Scoring History:
    timestamp            duration    number_of_trees    training_rmse    training_logloss    training_auc    training_pr_auc    training_lift    training_classification_error    validation_rmse    validation_logloss    validation_auc    validation_pr_auc    validation_lift    validation_classification_error
--  -------------------  ----------  -----------------  ---------------  ------------------  --------------  -----------------  ---------------  -------------------------------  -----------------  --------------------  ----------------  -------------------  -----------------  ---------------------------------
    2025-07-07 04:38:40  6.059 sec   0                  nan              nan                 nan             nan                nan              nan                              nan                nan                   nan               nan                  nan                nan
    2025-07-07 04:38:41  7.430 sec   1                  nan              nan                 nan             nan                nan              nan                              0.326617           0.641064              0.884336          0.759871             3.87758            0.1564

Variable Importances:
variable        relative_importance    scaled_importance    percentage
--------------  ---------------------  -------------------  ------------
relationship    2140.83                1                    0.478077
capital.gain    657.266                0.307014             0.146776
occupation      512.904                0.239582             0.114538
education       415.642                0.194149             0.0928183
age             227.563                0.106296             0.0508178
hours.per.week  156.1                  0.0729157            0.0348593
capital.loss    136.055                0.0635524            0.0303829
native.country  96.7295                0.0451831            0.021601
workclass       53.2384                0.0248681            0.0118888
fnlwgt          28.9179                0.0135078            0.00645776
marital.status  26.6713                0.0124584            0.00595606
sex             16.528                 0.00772036           0.00369093
race            9.49375                0.00443461           0.00212008
education.num   0.0694444              3.2438e-05           1.55079e-05

[tips]
Use `model.explain()` to inspect the model.
--
Use `h2o.display.toggle_user_tips()` to switch on/off this section.

In [ ]:
preds = model.predict(hf_test).as_data_frame()
submission = pd.DataFrame({'income': preds['predict']})

drf prediction progress: |███████████████████████████████████████████████████████| (done) 100%

/usr/local/lib/python3.11/dist-packages/h2o/job.py:81: UserWarning: Test/Validation dataset column 'native.country' has levels not trained on: ["Holand-Netherlands"]
  warnings.warn(w)
/usr/local/lib/python3.11/dist-packages/h2o/frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
معیار ارزیابی
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    معیاری که برای ارزیابی عملکرد مدل انتخاب کرده‌ایم، <code>F1-score</code> نام دارد و کلاس مثبت (<code>pos_label</code>) را معادل <code dir=ltr>>50K</code> فرض کرده‌ایم، به این معنی که مدل شما باید برای پیش‌بینی درست افراد پردرآمد عملکرد مناسبی داشته باشد.
    <br>
    پیشنهاد می‌شود با توجه به این معیار، عملکرد مدل خود را بر روی مجموعه‌ی آموزش یا اعتبارسنجی ارزیابی کنید و طبق نتایج به‌دست‌آمده پارامترهای مدل خود را بهتر تنظیم کنید.
</font>
</p>

In [ ]:
from sklearn.metrics import f1_score, classification_report

# پیش‌بینی روی داده اعتبارسنجی
y_val_pred = clf.predict(X_val)

# محاسبه F1-score برای کلاس مثبت 1 (یعنی >50K)
f1 = f1_score(y_val, y_val_pred, pos_label=1)

print(f"F1-score (class '>50K'): {f1:.4f}")
print(classification_report(y_val, y_val_pred, target_names=['<=50K', '>50K']))

NameError: name 'clf' is not defined

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font color="red"><b color='red'>توجه:</b></font>
<font face="vazirmatn" size=3>
 جهت کسب امتیاز کامل نیاز است تا پاسخ شما حداقل امتیاز <code>66</code> را با توجه به معیار معرفی‌شده کسب نماید.
</font>
</p>

In [ ]:
from sklearn.model_selection import train_test_split

# فرض می‌کنیم train_data دیتافریم اصلی شماست
train_df, val_df = train_test_split(train_data, test_size=0.2, random_state=42)

# حالا می‌توانید آنها را به H2OFrame تبدیل کنید
import h2o
h2o.init()

hf_train = h2o.H2OFrame(train_df)
hf_valid = h2o.H2OFrame(val_df)
hf_test = h2o.H2OFrame(test_data)  # اگر تست جدا هست

# فراموش نکن ستون هدف را دسته‌ای کن
hf_train['income'] = hf_train['income'].asfactor()
hf_valid['income'] = hf_valid['income'].asfactor()

Checking whether there is an H2O instance running at http://localhost:54321. connected.
Warning: Your H2O cluster version is (3 months and 9 days) old.  There may be a newer version available.
Please download and install the latest version from: https://h2o-release.s3.amazonaws.com/h2o/latest_stable.html

--------------------------  -----------------------------------------------------------------------------------------
H2O_cluster_uptime:         9 mins 58 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.7
H2O_cluster_version_age:    3 months and 9 days
H2O_cluster_name:           H2O_from_python_unknownUser_ktv66e
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.167 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://localhost:54321
H2O_connection_proxy:       {"http": null, "https": null, "colab_language_server": "/usr/colab/bin/language_service"}
H2O_internal_security:      False
Python_version:             3.11.13 final
--------------------------  -----------------------------------------------------------------------------------------

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

In [ ]:
from h2o.estimators import H2ORandomForestEstimator

feature_cols = train_df.drop(columns='income').columns.tolist()
target_col = 'income'

from h2o.estimators import H2ORandomForestEstimator

model = H2ORandomForestEstimator(ntrees=1, sample_rate=1, mtries=-2, max_depth=10,
                                 min_rows=8, min_split_improvement=1e-4,
                                 balance_classes=True, nfolds=5)

model.train(x=feature_cols, y=target_col, training_frame=hf_train, validation_frame=hf_valid)



performance = model.model_performance(valid=True)
print(performance)
print("F1 scores:", performance.F1())

drf Model Build progress: |██████████████████████████████████████████████████████| (done) 100%
ModelMetricsBinomial: drf
** Reported on validation data. **

MSE: 0.10773937101632092
RMSE: 0.3282367606108751
LogLoss: 0.6439222832235287
Mean Per-Class Error: 0.2034395905860459
AUC: 0.8848740367595549
AUCPR: 0.7586841111103455
Gini: 0.7697480735191098

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.39849353953836236
       <=50K    >50K    Error    Rate
-----  -------  ------  -------  --------------
<=50K  3322     433     0.1153   (433.0/3755.0)
>50K   363      882     0.2916   (363.0/1245.0)
Total  3685     1315    0.1592   (796.0/5000.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.398494     0.689063  29
max f2                       0.136519     0.777454  66
max f0point5                 0.610169     0.713366  14
max accuracy                 0.575891     0.85      16
max precision                1            0.956386  0
max recall                   0            1         100
max specificity              1            0.996272  0
max absolute_mcc             0.398494     0.582574  29
max min_per_class_accuracy   0.363851     0.813049  34
max mean_per_class_accuracy  0.30303      0.816466  40
max tns                      1            3741      0
max fns                      1            938       0
max fps                      0            3755      100
max tps                      0            1245      100
max tnr                      1            0.996272  0
max fnr                      1            0.753414  0
max fpr                      0            1         100
max tpr                      0            1         100

Gains/Lift Table: Avg response rate: 24.90 %, avg score: 24.73 %
group    cumulative_data_fraction    lower_threshold    lift       cumulative_lift    response_rate    score        cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  ---------  -----------------  ---------------  -----------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------  --------------------
1        0.0642                      1                  3.84091    3.84091            0.956386         1            0.956386                    1                   0.246586        0.246586                   284.091   284.091            0.242858
2        0.1384                      0.74461            2.86862    3.31964            0.714286         0.756083     0.82659                     0.869229            0.212851        0.459438                   186.862   231.964            0.42748
3        0.1708                      0.610169           2.30552    3.12726            0.574074         0.624078     0.778689                    0.822725            0.0746988       0.534137                   130.552   212.726            0.483804
4        0.2098                      0.575891           2.20369    2.95558            0.548718         0.577144     0.735939                    0.777074            0.0859438       0.62008                    120.369   195.558            0.546312
5        0.34                        0.364658           1.47441    2.38838            0.367127         0.387882     0.594706                    0.628036            0.191968        0.812048                   47.4408   138.838            0.62856
6        0.4024                      0.189441           0.862424   2.15175            0.214744         0.267405     0.535785                    0.572113            0.0538153       0.865863                   -13.7576  115.175            0.617128
7        0.5188                      0.05418            0.558937   1.79438            0.139175         0.113299     0.4468                      0.469172            0.0650602       0.930924                   -44.1063  79.4379            0.548767
8        0.683                       0.0102802          0.200559   1.41121            0.0499391        0.0213377    0.351391                    0.361508            0.0329317       0.963855                   -79.9441  41.1209            0.373975
9        0.737                       0.00387272         0.0743716  1.31326            0.0185185        0.00407252   0.327001                    0.335319            0.00401606      0.967871                   -92.5628  31.3258            0.307419
10       0.9424                      0.00029279         0.0195524  1.03129            0.00486855       0.000674775  0.256791                    0.262382            0.00401606      0.971888                   -98.0448  3.12898            0.0392644
11       1                           0                  0.488063   1                  0.121528         0            0.249                       0.247269            0.0281124       1                          -51.1937  0                  0
F1 scores: [[0.39849353953836236, 0.6890625000000001]]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
 پیش‌بینی برای داده تست و خروجی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    پس از مهندسی ویژگی و مدل‌سازی، الگوریتمی دارید که می‌تواند شما را از متغیرهای مستقل به متغیر هدف برساند.
    <br>
    از این مدل برای پیش‌بینی نمونه‌های موجود در مجموعه‌ی آزمون استفاده کنید و نتایج را در یک دیتافریم تک‌ستونه با نام <code>submission</code> و در قالب زیر آماده کنید. توجه داشته باشید که ترتیب پیش‌بینی شما اهمیت دارد یعنی به عنوان مثال پیش‌بینی مدل برای نمونه‌ی آزمون <code>m</code>ام را باید در ردیف <code>m</code>ام این دیتافریم ذخیره کنید.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|income|پیش‌بینی مدل شما (مقدار <code dir=ltr>>50K</code> یا <code dir=ltr><=50K</code>)|
    
</font>
</div>
</center>

In [ ]:


# ساخت دیتافریم نهایی برای ارسال
# پیش‌بینی روی داده تست
y_test_pred = clf.predict(X_val)

# تبدیل برچسب عددی به متنی
income_labels = np.where(y_test_pred == 1, '>50K', '<=50K')

# ساخت submission
submission = pd.DataFrame({'income': income_labels})
print(submission.head())

NameError: name 'clf' is not defined

In [ ]:
# فرض: model مدل آموزش‌دیده H2O و hf_test داده تست به صورت H2OFrame است

preds_df = model.predict(hf_test).as_data_frame()

# اگر ستون 'predict' شامل مقادیر عددی 0 و 1 است:
if preds_df['predict'].dtype != object:
    import numpy as np
    preds_df['predict'] = np.where(preds_df['predict'] == 1, '>50K', '<=50K')

# ساخت دیتافریم submission
submission = preds_df[['predict']].rename(columns={'predict': 'income'})

print(submission.head())

drf prediction progress: |███████████████████████████████████████████████████████| (done) 100%
  income
0  <=50K
1  <=50K
2   >50K
3  <=50K
4  <=50K

/usr/local/lib/python3.11/dist-packages/h2o/job.py:81: UserWarning: Test/Validation dataset column 'native.country' has levels not trained on: ["Holand-Netherlands"]
  warnings.warn(w)
/usr/local/lib/python3.11/dist-packages/h2o/frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [ ]:
import zipfile
import joblib

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

submission.to_csv('submission.csv', index=False)
file_names = ['income.ipynb', 'submission.csv']
compress(file_names)

File Paths:
['income.ipynb', 'submission.csv']

<h4 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
<b>راهنمایی</b>
</font>
</h4>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    ۱. توازن مجموعه‌داده را بررسی و مدیریت کنید.
    <br>
    ۲. برای مقادیر گم‌شده چه در هنگام آموزش و چه هنگام آزمون چاره‌ای بی‌اندیشید.
    <br>
    ۳. مقادیر گم‌شده ممکن است با عبارت دیگری به جز مقدار <code>NaN</code> نشان داده شده باشد.
    <br>
    ۴. ویژگی‌های دسته‌ای را به‌خوبی مدیریت کنید. توجه داشته باشید که ممکن است در هنگام آزمون با دسته‌ای مواجه شوید که در نمونه‌های آموزشی رخ نداده باشد.
    <br>
    ۵. برای تعیین حداکثر عمق درخت می‌توانید یکبار درخت را به شکل آزاد و کامل بسازید، سپس عمق آن را مشاهده کنید. سپس می‌توانید مقادیر کمتر از آن را برای حداکثر عمق آزمایش و تحلیل کنید.
    <br>
    ۶. برای ارزیابی مدل خود و کشف مدل بهتر می‌توانید بخشی از مجموعه‌داده را به عنوان مجموعه‌ی اعتبارسنجی جدا کنید یا اینکه از تکنیک‌های اعتبارسنجی متقاطع (cross-validation) و مانند آن کمک بگیرید.
</font>
</p>