<a href="https://colab.research.google.com/github/Taheri1400/machine-learning-projects/blob/main/tafrihi_solved.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
تفریحی
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
مقدمه و صورت مسئله
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    در این تمرین قصد داریم به پیشبینی دلیل سفر کاربران بپردازیم. برخی از کاربران مستربلیط به دلیل کاری و برخی دیگر به دلایل تفریحی به سفر می‌روند. به منظور شخصی‌سازی بیشتر و دقیق‌تر، مستربلیط قصد دارد بداند هر بلیط به چه دلیلی رزرو می‌شود.
    <br>
    حال از داده‌هایی که در اختیارتان قرار گرفته است استفاده کنید و مدلی آموزش دهید که تفریحی یا کاری بودن سفر را تشخیص دهد.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
وارد کردن کتابخانه‌های مورد نیاز
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    ابتدا کتابخانه‌های مورد نیازتان را وارد کنید.
</font>
</p>

In [ ]:
import pandas as pd
import numpy as np

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
معرفی مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
مجموعه داده آموزشی شامل ۱۰۱۰۱۷ سطر است که در جدول زیر، توضیحات هر ستون آمده است.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|Created|زمان ثبت بلیط|
|CancelTime|زمانی که مسافر بلیط را کنسل کرده است|
|DepartureTime|زمان حرکت|
|BillID|شناسه خرید|
|TicketID|شناسه بلیط|
|ReserveStatus|وضعیت پرداخت مشتری|
|UserID|شناسه کاربری|
|Male|آیا بلیط متعلق به زن است یا مرد|
|Price|قیمت بلیط بدون تخفیف|
|CouponDiscount|تخفیفی که شخص روی بلیط اعمال کرده است|
|From|مبدا سفر|
|To|مقصد سفر|
|Domestic|آیا سفر، داخلی است یا خارجی|
|VehicleType|جزئیات وسیله نقلیه را مشخص می‌کند|
|VehicleClass|آیا وسیله نقلیه، فرست‌کلس است یا نه|
|Vehicle|نوع وسیله نقلیه|
|Cancel|آیا بلیط کنسل شده‌است یا نه|
|HashPassportNumber_p|هش‌شده شماره پاسپورت|
|HashEmail|هش‌شده ایمیل|
|BuyerMobile|هش‌شده شماره موبایل|
|NationalCode|هش‌شده شماره‌ملی|
|TripReason|دلیل سفر|
    
</font>
</div>
</center>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    مجموعه داده آزمایش نیز مانند مجموعه آموزش است با این تفاوت که ستون <code>TripReason</code> که متغیر هدف مسئله است را در خود ندارد. مجموعه داده آزمایش ۴۳۲۹۳ سطر دارد.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
خواندن مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    در ابتدا نیاز است فایل‌های مجموعه‌داده را بخوانید. نمونه‌های آموزشی در فایل <code>train.csv</code> و نمونه‌های آزمون که باید دسته‌ی آن‌ها را پیش‌بینی کنید در فایل <code>test.csv</code> ذخیره شده‌اند. اگر لازم دانستید می‌توانید به دلخواه خود بخشی از دادگان آموزشی را به عنوان دادگان اعتبارسنجی نیز جدا کنید.
</font>
</p>

In [ ]:
train_data = pd.read_csv('train_data.csv')
train_data

,Created,CancelTime,DepartureTime,BillID,TicketID,ReserveStatus,UserID,Male,Price,CouponDiscount,...,Domestic,VehicleType,VehicleClass,TripReason,Vehicle,Cancel,HashPassportNumber_p,HashEmail,BuyerMobile,NationalCode
0,2022-10-23 09:38:49.110,NaN,2022-11-02 23:59:00,39710203,1091777.0,5,122885.0,True,6600000.0,34425.0,...,1,NaN,False,Work,Plane,0,NaN,66c7f29e3b92f3b77e20830ac29e7758037a53d2238a5b...,764974891906,477368495
1,2022-08-15 14:51:43.160,NaN,2022-08-18 04:15:00,38689463,1070902.0,5,876925.0,True,9500000.0,0.0,...,1,NaN,False,Int,Plane,0,NaN,b24634843858a4175d03422aa9e7211ec3b9f3ce4c481c...,27479149496,15987669
2,2022-09-20 17:25:27.250,NaN,2022-09-21 11:00:00,39245173,7624237.0,3,916640.0,False,2000000.0,0.0,...,1,VIP 2+1,True,Work,Bus,0,NaN,NaN,323657282999,667640412
3,2022-06-25 11:32:53.980,NaN,2022-06-26 08:30:00,37957585,2867547.0,2,NaN,False,40000.0,0.0,...,1,3 ستاره اتوبوسي,NaN,Int,Train,0,NaN,NaN,169459057632,392476186
4,2022-06-01 11:30:53.633,NaN,2022-06-02 23:00:00,37584530,7212559.0,3,NaN,True,1130000.0,0.0,...,1,اسکانیا تک صندلی ۳۱نفره,True,Int,Bus,0,NaN,NaN,408595008421,79497837
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101012,2022-06-01 00:20:14.280,NaN,2022-06-04 12:10:00,37579327,1050781.0,5,NaN,True,5900000.0,0.0,...,1,بوئینگ 737,False,Int,Plane,0,NaN,NaN,605105141718,103215806
101013,2022-10-29 20:54:31.330,NaN,2022-11-01 15:30:00,39789479,3085407.0,2,403095.0,True,926500.0,0.0,...,1,4 ستاره اتوبوسي نگين,NaN,Work,Train,0,NaN,NaN,414997568556,193262890
101014,2022-09-03 17:57:22.067,NaN,2022-09-13 09:30:00,38991563,2322052.0,5,528307.0,True,30000000.0,0.0,...,0,NaN,False,Int,InternationalPlane,0,47b8f2d9b5de7e0e0e7234c18a1aa0c4b35798e6cb46b4...,a4dcb7941ee3c8f7b1fc6a171015692bc961d65a84ad47...,99460830937,34732401
101015,2022-09-29 13:15:51.303,NaN,2022-09-29 17:30:00,39406503,7664730.0,3,797946.0,True,980000.0,0.0,...,1,25 نفره (VIP),True,Work,Bus,0,NaN,718bc52c3e88520531463b385998a1193e2821d518b60b...,487489926847,458338866
101016,2022-03-31 13:29:11.530,NaN,2022-04-05 17:10:00,36742809,2711094.0,2,NaN,True,3168000.0,0.0,...,1,4 ستاره 4 تخته ارگ,NaN,Work,Train,0,NaN,da0821178342aeaab37bb1e44c162660c7d3196ae2f987...,146462381941,999949622

In [ ]:
test_data = pd.read_csv('test_data.csv')
test_data

,Created,CancelTime,DepartureTime,BillID,TicketID,ReserveStatus,UserID,Male,Price,CouponDiscount,...,To,Domestic,VehicleType,VehicleClass,Vehicle,Cancel,HashPassportNumber_p,HashEmail,BuyerMobile,NationalCode
0,2022-07-22 12:52:35.293,NaN,2022-08-03 17:00:00,38372770,7429183.0,3,NaN,False,1220000.0,0.0,...,اصفهان,1,ماهانVIP مانیتوردار کاوه,True,Bus,0,NaN,7ec2bc45a1a56014c60beb9e6ae72e748563f270b5961e...,855578545022,752371627
1,2022-05-16 10:55:29.397,2022-05-18 11:35:15.643,2022-05-19 17:00:00,37348034,7147402.0,5,NaN,True,2830000.0,0.0,...,قم,1,VIP 2+1 / سیستم تهویه مطبوع / تخت شو,True,Bus,1,NaN,09731a27ab7323fa8a65a5d61a6f6cdf5b127a5d89d1af...,687891042993,926996211
2,2022-02-13 16:10:33.870,NaN,2022-02-15 22:45:00,36058084,6817410.0,3,NaN,True,1480000.0,0.0,...,اردبیل,1,25 نفره (VIP),True,Bus,0,NaN,NaN,515831406373,890191812
3,2022-05-01 17:56:18.530,NaN,2022-05-06 14:30:00,37140430,7093047.0,3,NaN,False,2450000.0,0.0,...,شیراز,1,Scania VIP 2+1,True,Bus,0,NaN,NaN,349742111820,941450742
4,2022-05-19 18:40:48.760,NaN,2022-05-21 12:30:00,37393459,2789874.0,2,135424.0,True,1965500.0,0.0,...,تهران,1,3 ستاره 6 تخته كوير,NaN,Train,0,NaN,a9b7344fa6dffcd85117f3b4209a379600a66019dbfb57...,63387630789,575541645
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43288,2022-10-06 16:57:16.053,NaN,2022-10-07 21:00:00,39515216,7693401.0,3,NaN,True,800000.0,0.0,...,زاهدان,1,classicus 2+2,True,Bus,0,NaN,084471d0e58161bf494c8d540208e17d2b3cb0ea3eff70...,793972140866,560495589
43289,2022-06-14 13:19:26.413,NaN,2022-06-18 07:15:00,37773311,1055789.0,5,NaN,False,7827000.0,0.0,...,تهران,1,NaN,False,Plane,0,NaN,NaN,574095530769,194295556
43290,2022-10-23 15:48:03.947,NaN,2022-10-23 20:25:00,39714891,7747506.0,3,NaN,False,370000.0,0.0,...,قم,1,مارال تک صندلی ۳۰نفره,True,Bus,0,NaN,NaN,82614935547,704290882
43291,2022-09-18 21:18:01.730,2022-09-19 15:40:44.707,2022-09-20 20:00:00,39215621,7620724.0,5,950877.0,True,2520000.0,0.0,...,مسجدسلیمان,1,VIP 2+1 / شارژر یو اس بی / سیستم تهویه مطبوع ...,True,Bus,1,NaN,57f1cffdba91d23d66f923c5defcd40caa8d317f8bcfbc...,242545550300,513968890
43292,2022-07-27 22:08:17.510,2022-07-30 19:19:29.357,2022-08-03 21:00:00,38449571,7451530.0,5,633165.0,True,2150000.0,0.0,...,تهران,1,VIP درسا مانیتوردار با پک بهداشتی,True,Bus,1,NaN,NaN,965279078669,20749399

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
پیش‌پردازش و مهندسی ویژگی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    در این سوال شما می‌توانید از هر تکنیک پیش‌پردازش/مهندسی ویژگی که در فصل‌های گذشته آموختید، استفاده کنید.
    <br>
    تکنیک‌هایی که استفاده می‌کنید به شکل مستقیم مورد ارزیابی توسط سامانه داوری قرار <b>نمی‌گیرند.</b> بلکه همه آن‌ها در دقت مدل شما تاثیر خواهند گذاشت؛ بنابراین هر چه پیش‌پردازش/مهندسی ویژگی بهتری انجام دهید تا دقت مدل بهبود پیدا کند، امتیاز بیشتری از این سوال کسب خواهید کرد.
</font>
</p>

In [ ]:
train_data.isna().sum()

Created                     0
CancelTime              60259
DepartureTime               0
BillID                      0
TicketID                    0
ReserveStatus               0
UserID                  41126
Male                        0
Price                       0
CouponDiscount              0
From                        0
To                          0
Domestic                    0
VehicleType              5300
VehicleClass            27023
TripReason                  0
Vehicle                     0
Cancel                      0
HashPassportNumber_p    70412
HashEmail               40738
BuyerMobile                 0
NationalCode                0
dtype: int64

In [ ]:
test_data.isna().sum()

Created                     0
CancelTime              36746
DepartureTime               0
BillID                      0
TicketID                    0
ReserveStatus               0
UserID                  24989
Male                        0
Price                       0
CouponDiscount              0
From                        0
To                          0
Domestic                    0
VehicleType              3377
VehicleClass            16338
Vehicle                     0
Cancel                      0
HashPassportNumber_p    42899
HashEmail               24756
BuyerMobile                 0
NationalCode                0
dtype: int64

In [ ]:
train_data=train_data.iloc[:-1]

In [ ]:
drop_cols = ['HashPassportNumber_p', 'HashEmail', 'BuyerMobile', 'NationalCode', 'TicketID', 'BillID', 'UserID']
train_data.drop(columns=drop_cols, inplace=True)
test_data.drop(columns=drop_cols, inplace=True)

/tmp/ipython-input-6-597454661.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data.drop(columns=drop_cols, inplace=True)

In [ ]:
for col in ['Created', 'CancelTime', 'DepartureTime']:
    train_data[col] = pd.to_datetime(train_data[col], errors='coerce')
    test_data[col] = pd.to_datetime(test_data[col], errors='coerce')

/tmp/ipython-input-8-2278117316.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[col] = pd.to_datetime(train_data[col], errors='coerce')
/tmp/ipython-input-8-2278117316.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[col] = pd.to_datetime(train_data[col], errors='coerce')
/tmp/ipython-input-8-2278117316.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[col] = pd.to_datetime(train_data[col], errors='coerce')

In [ ]:
train_data['hour_created'] = train_data['Created'].dt.hour
test_data['hour_created'] = test_data['Created'].dt.hour

/tmp/ipython-input-9-2927904903.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data['hour_created'] = train_data['Created'].dt.hour

In [ ]:
train_data['dayofweek_created'] = train_data['Created'].dt.dayofweek
test_data['dayofweek_created'] = test_data['Created'].dt.dayofweek

/tmp/ipython-input-10-3748055376.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data['dayofweek_created'] = train_data['Created'].dt.dayofweek

In [ ]:
train_data['time_to_departure'] = (train_data['DepartureTime'] - train_data['Created']).dt.total_seconds() / 3600
test_data['time_to_departure'] = (test_data['DepartureTime'] - test_data['Created']).dt.total_seconds() / 3600

/tmp/ipython-input-11-399857306.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data['time_to_departure'] = (train_data['DepartureTime'] - train_data['Created']).dt.total_seconds() / 3600

In [ ]:
train_data.fillna({'CouponDiscount': 0, 'VehicleClass': False, 'Male': False, 'Cancel': 0}, inplace=True)
test_data.fillna({'CouponDiscount': 0, 'VehicleClass': False, 'Male': False, 'Cancel': 0}, inplace=True)

/tmp/ipython-input-12-2378722253.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train_data.fillna({'CouponDiscount': 0, 'VehicleClass': False, 'Male': False, 'Cancel': 0}, inplace=True)
/tmp/ipython-input-12-2378722253.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data.fillna({'CouponDiscount': 0, 'VehicleClass': False, 'Male': False, 'Cancel': 0}, inplace=True)
/tmp/ipython-input-12-2378722253.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data.fillna({'CouponDiscount': 0, 'VehicleClass': False, 'Male': False, 'Cancel': 0}, inplace=True)
/tmp/ipython-input-12-2378722253.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test_data.fillna({'CouponDiscount': 0, 'VehicleClass': False, 'Male': False, 'Cancel': 0}, inplace=True)

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
train_data['TripReason'] = le.fit_transform(train_data['TripReason'])  # Work=1, Int=0

/tmp/ipython-input-13-380390976.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data['TripReason'] = le.fit_transform(train_data['TripReason'])  # Work=1, Int=0

In [ ]:
cat_cols = ['From', 'To', 'VehicleType', 'Vehicle']
train_data[cat_cols] = train_data[cat_cols].fillna('missing')
test_data[cat_cols] = test_data[cat_cols].fillna('missing')

train_data = pd.get_dummies(train_data, columns=cat_cols)
test_data = pd.get_dummies(test_data, columns=cat_cols)

# تطبیق ستون‌های آموزش و آزمون
test_data = test_data.reindex(columns=train_data.drop(columns='TripReason').columns, fill_value=0)

/tmp/ipython-input-14-2794375121.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[cat_cols] = train_data[cat_cols].fillna('missing')

In [ ]:
train_data['CancelTime'].fillna(pd.Timestamp('2100-01-01'), inplace=True)
test_data['CancelTime'].fillna(pd.Timestamp('2100-01-01'), inplace=True)

/tmp/ipython-input-15-1911589345.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_data['CancelTime'].fillna(pd.Timestamp('2100-01-01'), inplace=True)
/tmp/ipython-input-15-1911589345.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test_data['CancelTime'].fillna(pd.Timestamp('2100-01-01'), inplace=True)

In [ ]:
bool_cols = ['Male', 'VehicleClass', 'Cancel']

# جایگذاری با False یا 0 (پیش‌فرض محافظه‌کارانه)
train_data[bool_cols] = train_data[bool_cols].fillna(False)
test_data[bool_cols] = test_data[bool_cols].fillna(False)

In [ ]:
numeric_cols = ['Price', 'CouponDiscount']

# جایگذاری با میانگین یا صفر
for col in numeric_cols:
    mean_val = train_data[col].mean()
    train_data[col].fillna(mean_val, inplace=True)
    test_data[col].fillna(mean_val, inplace=True)

/tmp/ipython-input-17-2964761762.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_data[col].fillna(mean_val, inplace=True)
/tmp/ipython-input-17-2964761762.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test_data[col].fillna(mean_val, inplace=True)

In [ ]:
test_data.isna().sum()

Created                       0
CancelTime                    0
DepartureTime                 0
ReserveStatus                 0
Male                          0
                             ..
VehicleType_۴۷MANصندلی        0
Vehicle_Bus                   0
Vehicle_InternationalPlane    0
Vehicle_Plane                 0
Vehicle_Train                 0
Length: 3659, dtype: int64

In [ ]:
train_data

,Created,CancelTime,DepartureTime,ReserveStatus,Male,Price,CouponDiscount,Domestic,VehicleClass,TripReason,...,VehicleType_۲۹نفره وی آی پی شارژردار,VehicleType_۲۹نفره وی آی پی ۳محوره,VehicleType_۳۰نفره تک صندلی مارالVIP (همسفر),VehicleType_۳۲VIPنفره,VehicleType_۴۵۷ چهل نفره,VehicleType_۴۷MANصندلی,Vehicle_Bus,Vehicle_InternationalPlane,Vehicle_Plane,Vehicle_Train
0,2022-10-23 09:38:49.110,2100-01-01,2022-11-02 23:59:00,5,True,6600000.0,34425.0,1,False,1,...,False,False,False,False,False,False,False,False,True,False
1,2022-08-15 14:51:43.160,2100-01-01,2022-08-18 04:15:00,5,True,9500000.0,0.0,1,False,0,...,False,False,False,False,False,False,False,False,True,False
2,2022-09-20 17:25:27.250,2100-01-01,2022-09-21 11:00:00,3,False,2000000.0,0.0,1,True,1,...,False,False,False,False,False,False,True,False,False,False
3,2022-06-25 11:32:53.980,2100-01-01,2022-06-26 08:30:00,2,False,40000.0,0.0,1,False,0,...,False,False,False,False,False,False,False,False,False,True
4,2022-06-01 11:30:53.633,2100-01-01,2022-06-02 23:00:00,3,True,1130000.0,0.0,1,True,0,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101011,2022-07-27 12:59:36.487,2100-01-01,2022-08-29 17:05:00,2,False,4832000.0,0.0,1,False,0,...,False,False,False,False,False,False,False,False,False,True
101012,2022-06-01 00:20:14.280,2100-01-01,2022-06-04 12:10:00,5,True,5900000.0,0.0,1,False,0,...,False,False,False,False,False,False,False,False,True,False
101013,2022-10-29 20:54:31.330,2100-01-01,2022-11-01 15:30:00,2,True,926500.0,0.0,1,False,1,...,False,False,False,False,False,False,False,False,False,True
101014,2022-09-03 17:57:22.067,2100-01-01,2022-09-13 09:30:00,5,True,30000000.0,0.0,0,False,0,...,False,False,False,False,False,False,False,True,False,False
101015,2022-09-29 13:15:51.303,2100-01-01,2022-09-29 17:30:00,3,True,980000.0,0.0,1,True,1,...,False,False,False,False,False,False,True,False,False,False

In [ ]:
train_data['was_canceled'] = train_data['CancelTime'].notna().astype(int)
train_data['cancel_delay_hours'] = (train_data['CancelTime'] - train_data['Created']).dt.total_seconds() / 3600
train_data['cancel_delay_hours'].fillna(-1, inplace=True)  # برای بلیط‌هایی که کنسل نشده‌اند

test_data['was_canceled'] = test_data['CancelTime'].notna().astype(int)
test_data['cancel_delay_hours'] = (test_data['CancelTime'] - test_data['Created']).dt.total_seconds() / 3600
test_data['cancel_delay_hours'].fillna(-1, inplace=True)

/tmp/ipython-input-35-2774102331.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_data['cancel_delay_hours'].fillna(-1, inplace=True)  # برای بلیط‌هایی که کنسل نشده‌اند
/tmp/ipython-input-35-2774102331.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test_data['cancel_delay_hours'].fillna(-1, inplace=True)

In [ ]:
train_data.drop(columns=['Created', 'DepartureTime', 'CancelTime'], inplace=True)
test_data.drop(columns=['Created', 'DepartureTime', 'CancelTime'], inplace=True)

In [ ]:
print(X_train.select_dtypes(include=['datetime64[ns]']).columns)

Index(['Created', 'CancelTime', 'DepartureTime'], dtype='object')

In [ ]:
from sklearn.model_selection import train_test_split

# متغیر هدف
y = train_data['TripReason']

# فقط حذف ستون هدف از ویژگی‌ها (چون بقیه قبلاً حذف شده‌اند)
X = train_data.drop(columns=['TripReason'])

# تقسیم داده به آموزش و اعتبارسنجی
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
مدل‌سازی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    حال که داده را پاکسازی کرده و احتمالا ویژگی‌هایی را به آن افزوده یا از آن حذف کرده‌اید، وقت آن است که مدلی آموزش دهید که بتواند متغیر هدف این مسئله را پیش‌بینی کند.
    <br>
    بر خلاف سایر تمرین‌های کالج، در این تمرین شما مجاز هستید از هر مدلی که آموخته‌اید استفاده کنید. به عبارت بهتر، هدف این سوال پیش‌بینی هرچه بهتر متغیر هدف مسئله است. انتظار ما این است که نحوه کار با کتابخانه‌های یادگیری ماشین را در حدی آموخته باشید که بتوانید با بهترین عملکرد، مسئله را حل کنید!
</font>
</p>

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, f1_score

model_rf = RandomForestClassifier(n_estimators=300, max_depth=20, random_state=42)
model_rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=20, n_estimators=300, random_state=42)

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
معیار ارزیابی
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    معیاری که برای ارزیابی عملکرد مدل انتخاب کرده‌ایم، <code>f1_score</code> نام دارد.
    <br>
    این معیار، سنجه ارزیابی کیفیت مدل شماست. به عبارت بهتر در سامانه داوری هم از همین معیار برای نمره‌دهی استفاده شده است.
    <br>
    پیشنهاد می‌شود با توجه به این معیار، عملکرد مدل خود را بر روی مجموعه داده آموزش یا اعتبارسنجی ارزیابی کنید.
</font>
</p>

In [ ]:
# evaluate model
from sklearn.metrics import  f1_score, classification_report, confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import f1_score, classification_report, confusion_matrix

# پیش‌بینی روی داده اعتبارسنجی
y_val_pred = model_rf.predict(X_val)


f1 = f1_score(y_val, y_val_pred, average='weighted')
print(f"F1-score (weighted): {f1:.4f}")


print("\nClassification Report:")
print(classification_report(y_val, y_val_pred, target_names=['Int', 'Work']))


print("\nConfusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))

F1-score (weighted): 0.7600

Classification Report:
              precision    recall  f1-score   support

         Int       0.79      0.63      0.70      8942
        Work       0.75      0.87      0.80     11262

    accuracy                           0.76     20204
   macro avg       0.77      0.75      0.75     20204
weighted avg       0.77      0.76      0.76     20204


Confusion Matrix:
[[5653 3289]
 [1468 9794]]

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font color="red"><b color='red'>توجه:</b></font>
<font face="vazirmatn" size=3>
 جهت کسب امتیاز کامل نیاز است تا پاسخ شما حداقل امتیاز <code>75%</code> را با توجه به معیار معرفی‌شده کسب نماید.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
 پیش‌بینی برای داده تست و خروجی
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    پس از مهندسی ویژگی و مدلسازی، الگوریتمی دارید که می‌تواند شما را از متغیرهای مستقل به متغیر هدف برساند.
    <br>
    از این مدل برای پیش‌بینی نمونه‌های موجود در داده تست استفاده کنید و نتایج را در قالب جدول (<code>dataframe</code>) زیر آماده کنید.
</font>
</p>

<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    
|ستون|توضیحات|
|------|---|
|TripReason|دلیل سفر|
    
</font>
</div>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    اسم دیتافریم باید <i>submission</i> باشد؛ در غیر این صورت، سامانه داوری نمی‌تواند تلاش‌ شما را ارزیابی کند.
    <br>
    این دیتافریم تنها شامل ۱ ستون با اسم <i>TripReason</i> است و ۴۳۲۹۳ سطر دارد.
    <br>
    به ازای هر سطر موجود در دیتافریم <i>test</i> شما باید یک مقدار پیشبینی شده داشته باشید.
    <br>
    جدول زیر، ۵ سطر ابتدایی دیتافریم <code>submission</code> را نشان می‌دهد. البته در جواب شما، مقادیر ستون <i>TripReason</i> ممکن است متفاوت باشد.
</font>
</p>

<div style="text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    
||TripReason|
|----|-----|
|0|Work|
|1|Work|
|2|Int|
|3|Int|
|4|Work|

</font>
</div>

In [ ]:
test_data_prepared = test_data.drop(columns=['Created', 'DepartureTime', 'CancelTime'], errors='ignore')

# اگه لازم داری ستون‌های متنی رو encode کردی، باید این کار رو روی داده تست هم انجام بدی.

# 2. پیش‌بینی روی داده تست
test_preds = model_rf.predict(test_data_prepared)
# نگاشت عددی به رشته‌ای
label_map = {0: 'Int', 1: 'Work'}

# فرض بر اینه test_preds عددی است
test_preds_str = [label_map[p] for p in test_preds]

submission = pd.DataFrame({'TripReason': test_preds_str})

# 3. ساخت دیتافریم submission با ستون TripReason

submission

      TripReason
0           Work
1           Work
2           Work
3           Work
4           Work
...          ...
43288       Work
43289       Work
43290       Work
43291       Work
43292       Work

[43293 rows x 1 columns]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [ ]:
import zipfile
import joblib

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

submission.to_csv('submission.csv', index=False)
file_names = ['tafrihi.ipynb', 'submission.csv']
compress(file_names)

File Paths:
['tafrihi.ipynb', 'submission.csv']